In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('dados/titanic_dataset.csv') 
'''df significa DataFrame, que é uma estrutura de dados bidimensional, semelhante a uma tabela, onde os dados são organizados 
em linhas e colunas.'''

# Visualização inicial dos dados
Aqui eu visualizei as primeiras linhas do dataset para entender como os dados estão organizados e quais colunas existem.

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Estrutura dos dados
Aqui eu verifiquei as informações gerais do dataset, como quantidade de linhas, tipos das colunas e presença de valores nulos.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# Verificando os valores 
Aqui eu verifiquei a estrutura dos dados e identifiquei a presença de valores faltantes em algumas colunas.

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Tratamento dos dados
A coluna Cabin foi removida porque possui muitos valores nulos, o que pode prejudicar a análise.

In [6]:
df = df.drop(columns=['Cabin'])

# Preenchendo valores faltantes
A coluna Age tinha valores faltando, então preenchi esses valores com a média das idades.

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Tratamento dos dados
A coluna Embarked tinha poucos valores nulos, então optei por remover essas linhas.

In [8]:
df = df.dropna(subset=['Embarked'])

# Conferência dos dados
Após o tratamento, visualizei novamente os dados para garantir que as alterações foram aplicadas corretamente.

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

# Verificando valores diferentes
Aqui eu verifiquei quantos valores diferentes existem em cada coluna do dataset.

In [10]:
df.nunique()

PassengerId    889
Survived         2
Pclass           3
Name           889
Sex              2
Age             89
SibSp            7
Parch            7
Ticket         680
Fare           247
Embarked         3
dtype: int64